
# (PART\*) 巻末資料 {-}

# オンライン資料 {-}

この資料を作る上で参考になった資料を以下に載せておく。可視化やデータハンドリングについて、より詳しく知りたくなった場合は、これらの資料を参考にするとよいだろう。

- Winston Chang. *Cookbook for R.*　http://www.cookbook-r.com/Graphs/

    - ggplot2の様々なサンプル集。とにかく手を動かして覚えるタイプの教科書。
  
    - ちなみに日本語版の書籍が売られている。
  
    - *Rグラフィックスクックブックーggplot2によるグラフ作成のレシピ集*　https://www.amazon.co.jp/Rグラフィックスクックブック-―ggplot2によるグラフ作成のレシピ集-Winston-Chang/dp/4873116538

- Claus O. Wilke. *Fundamentals of Data Visualization.*　https://serialmentor.com/dataviz/

    - 可視化やデザインの基本について教えてくれる。
  
    - このサイト自体にコードは載っていないが、可視化において注意しなければならないことがたくさん書いてある。
  
    - 筆者のGitHubページに行けばコードも見ることができる。
  
- Hadley Wickham. *Elegant Graphics for Data Analysis.*　https://github.com/hadley/ggplot2-book

    - ggplot2を基本から知りたい人向け。
  
    - 英語版の書籍が売られている。
  
    - *ggplot2: Elegant Graphics for Data Analysis (Use R!)*　https://www.amazon.co.jp/ggplot2-Elegant-Graphics-Data-Analysis/dp/331924275X/ref=pd_lpo_sbs_14_t_0?_encoding=UTF8&psc=1&refRID=2MNMAP5V2NFH89YZG5AR

- Kieran Healy. *Data Visualization: A Practical Introduction.* https://socviz.co/index.html#preface

    - ggplot2＋可視化の入門書。最近人気の書籍のオンライン版（※全然読んでいない）。
    
    - *Fundamentals of Data Visualization*とは違い、コードも載っている。
    
    - *Data Visualization: A Practical Introduction.* https://www.amazon.co.jp/Data-Visualization-Introduction-Kieran-Healy/dp/0691181624

<br>

もちろん、日本語でもたくさんわかりやすい解説がある（そもそもこの資料が必要ないのでは？と思うレベルで既にたくさんある）ので、もっと知りたくなったら検索して調べてみてほしい。
